services:
  - type: web
    name: frext-crm
    runtime: docker
    plan: free
    region: singapore
    dockerfilePath: ./Dockerfile
    healthCheckPath: /healthz
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URL
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: ALLOW_SIGNUP
        value: "false"
