import { useState } from "react";
import { Link } from "react-router-dom";
import { ArrowRight, ArrowDown, ArrowUpRight, Users, LayoutDashboard, Handshake, CheckSquare, Activity, Check, LockKeyhole, TrendingUp, MoreHorizontal, Building2 } from "lucide-react";
import { useAuth } from "../hooks/useAuth";
import "./landing.css";

export function FrextBrand() {
  return <Link className="frext-brand" to="/" aria-label="Frext CRM home"><span className="frext-mark">f<span>.</span></span><span>frext<span className="frext-brand-sub">CRM</span></span></Link>;
}

export default function Landing() {
  const { user } = useAuth();
  const [view, setView] = useState("Overview");
  const destination = user ? "/dashboard" : "/login";
  return <div className="frext-public">
    <header className="frext-header frext-wrap"><FrextBrand /><nav aria-label="Main navigation"><a href="#workspace">Workspace</a><a href="#workflow">How it works</a></nav><Link className="frext-nav-login" to={destination}>{user ? "Open dashboard" : "Admin sign in"}<ArrowUpRight size={16} /></Link></header>
    <main>
      <section className="frext-hero frext-wrap">
        <div className="frext-hero-copy"><p className="frext-eyebrow"><span /> YOUR CUSTOMER WORKSPACE</p><h1>Good relationships.<br /><em>Better business.</em></h1><p className="frext-intro">A clear view of your customers, your pipeline, and what needs to happen next. Give your team one place to get the work done.</p><div className="frext-actions"><Link className="frext-button" to={destination}>{user ? "Open your workspace" : "Sign in to your workspace"}<ArrowRight size={17} /></Link><a className="frext-text-link" href="#workspace">Take a closer look <ArrowDown size={13} style={{ display: "inline", marginLeft: 8 }} /></a></div><p className="frext-access"><LockKeyhole size={13} /> A dedicated workspace for your business and team.</p></div>
        <div className="frext-relationship" aria-label="Illustrative customer relationship preview">
          <div className="frext-art-caption"><span className="frext-live-dot" /> THE RELATIONSHIP COMES FIRST <span>01</span></div>
          <div className="frext-contact-card"><div className="frext-contact-top"><span className="frext-company-icon"><Building2 size={25} strokeWidth={1.5}/></span><span className="frext-contact-status">In conversation</span><MoreHorizontal size={19}/></div><p className="frext-contact-company">Northstar Studio</p><span className="frext-contact-sub">Brand & design consultancy</span><div className="frext-contact-detail"><span>ACCOUNT OWNER</span><div><span className="frext-person-avatar">JD</span> Jamie Davis <span className="frext-contact-label">Sales</span></div></div><div className="frext-contact-next"><span>Next step</span><strong>Make the conversation count.</strong><p>Proposal follow-up <span>Today, 10:00</span></p></div></div>
          <div className="frext-success-note"><span><Check size={16}/></span><div><strong>A clear next step. Every time.</strong><p>Customer context, always close at hand.</p></div></div>
          <div className="frext-art-foot"><span>From first hello to a lasting relationship.</span><ArrowUpRight size={20}/></div>
        </div>
      </section>
      <section className="frext-wrap frext-workspace-section" id="workspace" aria-label="Workspace preview">
        <div className="frext-preview-label"><span>YOUR DAY, AT A GLANCE</span><span>Interactive preview &middot; Sample data</span></div>
        <div className="frext-preview">
          <aside className="frext-preview-sidebar"><div className="frext-preview-brand" aria-hidden="true">f<span>.</span></div>{[{name:"Overview",icon:LayoutDashboard},{name:"Customers",icon:Users},{name:"Pipeline",icon:Handshake},{name:"Tasks",icon:CheckSquare}].map(({name,icon:Icon})=><button type="button" key={name} title={name} aria-label={name + " preview"} aria-pressed={view===name} onClick={()=>setView(name)} className={view===name?"selected":""}><Icon size={19}/></button>)}<span className="frext-avatar">JD</span></aside>
          <div className="frext-preview-main"><div className="frext-preview-top"><span>Workspace <span>/ {view}</span></span><span className="frext-preview-team">Acme sales team</span></div><div className="frext-preview-heading"><div><p>MONDAY, 09 SEPTEMBER</p><h2>A little clarity for the week ahead.</h2></div><span className="frext-period"><span className="frext-live-dot"/> This month</span></div>
            <div className="frext-metrics">{[["Active customers","128","Relationships in progress"],["Open pipeline","\u20b98,40,000","Across 24 opportunities"],["Tasks due today","06","Your next steps, in order"]].map(([label,value,note])=><div key={label}><p>{label}</p><strong>{value}</strong><span>{note}</span></div>)}</div>
            {view === "Overview" || view === "Pipeline" ? <div className="frext-preview-bottom"><div className="frext-pipeline"><div className="frext-panel-title"><h3>Deal pipeline</h3><span>24 open deals</span></div>{[["Lead",9,90,"\u20b93,20,000"],["Qualified",7,72,"\u20b92,40,000"],["Proposal",5,52,"\u20b91,80,000"],["Negotiation",3,33,"\u20b91,00,000"]].map(([label,count,width,value])=><div className="frext-pipeline-row" key={label}><span>{label}</span><div><i style={{width:width+"%"}} /></div><span>{count}</span><strong>{value}</strong></div>)}</div><div className="frext-followups"><div className="frext-panel-title"><h3>Next up</h3><span>Today</span></div>{[["Proposal follow-up","Northstar Studio","10:00"],["Review account notes","Atlas & Co.","11:30"],["Schedule a check-in","Fieldwork Labs","14:00"]].map(([title,company,time])=><div className="frext-followup" key={title}><span className="frext-check-box"/><div><strong>{title}</strong><span>{company}</span></div><time>{time}</time></div>)}</div></div> : <div className="frext-preview-table"><div className="frext-panel-title"><h3>{view === "Customers" ? "People behind the pipeline" : "A plan for the day"}</h3><span>{view === "Customers" ? "Customer directory" : "Team task list"}</span></div>{(view === "Customers" ? [["NS","Northstar Studio","Design consultancy","In conversation"],["AC","Atlas & Co.","Professional services","Active customer"],["FL","Fieldwork Labs","Technology","New opportunity"]] : [["01","Send the revised proposal","Northstar Studio","Due today"],["02","Review the account notes","Atlas & Co.","In progress"],["03","Plan the next conversation","Fieldwork Labs","Scheduled"]]).map(([initials,title,detail,status])=><div className="frext-directory-row" key={title}><span>{initials}</span><div><strong>{title}</strong><p>{detail}</p></div><span className="frext-directory-status">{status}</span><ArrowUpRight size={14}/></div>)}</div>}
          </div>
        </div>
      </section>
      <section className="frext-capabilities frext-wrap" id="workflow"><div className="frext-section-heading"><p className="frext-eyebrow">BUILT AROUND THE WAY YOU WORK</p><h2>Everything connected.<br />Nothing lost in the handover.</h2></div><div className="frext-feature-grid">{[{n:"01",icon:Users,title:"Know the customer",text:"Keep contact details and notes together, so every conversation starts with the right context."},{n:"02",icon:Handshake,title:"Keep deals moving",text:"Follow each opportunity through your pipeline and see where your team's attention is needed."},{n:"03",icon:CheckSquare,title:"Follow through",text:"Assign tasks, track progress, and review activity. Make the next step clear for everyone."}].map(({n,icon:Icon,title,text})=><article key={n}><div className="frext-feature-top"><Icon size={23} strokeWidth={1.5}/><span>{n}</span></div><h3>{title}</h3><p>{text}</p></article>)}</div></section>
      <section className="frext-cta frext-wrap"><div><p className="frext-eyebrow">READY FOR THE WORKDAY</p><h2>Your team. Your customers.<br />One shared view.</h2><p><Check size={15}/> Customer records <Check size={15}/> Deal tracking <Check size={15}/> Team tasks</p></div><div><Link className="frext-button" to={destination}>{user ? "Go to dashboard" : "Admin sign in"}<ArrowRight size={17}/></Link><span className="frext-cta-note">Use your existing workspace account.</span></div></section>
    </main><footer className="frext-footer frext-wrap"><FrextBrand/><span>Customer relationships, thoughtfully managed.</span><span>&copy; {new Date().getFullYear()} Frext</span></footer>
  </div>;
}
